apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-74
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/michaelkotelnikov/argocd-bench-git-generator.git
      revision: master
      directories:
      - path: chart/app-74/values/*
  template:
    metadata:
      name: 'app-74-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelkotelnikov/argocd-bench-git-generator.git
        targetRevision: master
        path: chart/app-74/
        helm:
          valueFiles:
          - 'values/{{path.basename}}/values.yaml'
      destination:
        name: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true